basePath: /
definitions:
  models.ResponseSucces:
    properties:
      message:
        type: string
      result: {}
      success:
        type: boolean
    type: object
  models.UpdateStatusRequest:
    properties:
      status:
        type: boolean
    type: object
  utils.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  utils.RegisterRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    type: object
host: localhost:8011
info:
  contact: {}
  description: This is a Documentation API for Admin Pages
  title: Admin Pages
  version: "1.0"
paths:
  /admin/order/{id}:
    get:
      description: Get paginated detail of orders
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseSucces'
      security:
      - BearerAuth: []
      summary: Get detail orders
      tags:
      - Orders
  /admin/order/list:
    get:
      description: Get paginated list of orders with optional filters
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: Filter by order number
        in: query
        name: ordernumber
        type: string
      - description: Filter by status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseSucces'
      security:
      - BearerAuth: []
      summary: Get list orders
      tags:
      - Orders
  /admin/order/status/{id}:
    put:
      description: Update the status of an order by ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Status update info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpdateStatusRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseSucces'
      security:
      - BearerAuth: []
      summary: Update order status
      tags:
      - Orders
  /auth/login:
    post:
      description: Login user and get JWT token
      parameters:
      - description: Login Info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/utils.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseSucces'
      summary: Login user
      tags:
      - Auth
  /auth/register:
    post:
      description: Register user and Hash Password
      parameters:
      - description: Register Info
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/utils.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseSucces'
      summary: Register user
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
